### ISSUE TITLE
Numerical keypad for (phone) number input

### ISSUE THREAD

**Issue by habi** [bryceco/GoMap#511] opened 2021-03-13 16:42 UTC
When entering a phone number it would be awesome if the numerical keyboard is shown￼, making it easier/faster to add the correct number.

**Comment by habi** [comment] 2021-03-13 16:44
I have no clue if this works analogous in the app as with HTML, but I'm thinking of something like this: https://danf.ca/blog/2013/09/19/input-type-number-and-ios-numeric-keypad/

**Comment by bryceco** [comment] 2021-03-13 16:48
Yeah, the issue is that the numeric keyboard doesn't have a Done button like the other keyboards do, although that can be addressed by doing a little extra work to add the bar on top with a Done button.

**Comment by patricks** [comment] 2023-02-26 17:47
I checked a few things for this issue:

Changing the `keyboardType` to `.phonePad` would look like this:
![IMG_0211](https://user-images.githubusercontent.com/132167/221426558-5ba5b584-adf1-4d54-a825-001706641610.PNG)
![IMG_0210](https://user-images.githubusercontent.com/132167/221426568-1013fdd9-0826-4f65-82f8-fdc515f6d3ab.PNG)

Problem with this solution is that there is no `-` key to enter extension numbers.
The `Done` button could be easily added to the Toolbar above.

Changing the `keyboardType` to `.numbersAndPunctuation` would look like this:
![IMG_0212](https://user-images.githubusercontent.com/132167/221426736-25fb9813-6ce4-49b2-9102-ecd61af23e59.PNG)

The benefit would be that the user doesn't need do switch to the numerical keyboard.

Additionally we could check if settings the `textContentType` to `.telephoneNumber` would help.

I personally would change the `keyboardType` to `.numbersAndPunctuation` for phone numbers. What are your opinions?

**Comment by bryceco** [comment] 2023-02-26 18:01
There's a new TelephoneToolbar that gets attached to phone numbers in Common Tags. We just need to add that to KeyValueTableCell so it appears in All Tags as well.

**Closed** 2023-02-28 21:49 UTC

**Comment by bryceco** [comment] 2023-02-28 22:05
@patricks If you're interested a related task is to move the code related to func updateAssociatedContent() into the relevant presets in the Common Tags screen. It would require refactoring the logic and associated views into a separate class or classes.

**Comment by bryceco** [comment] 2023-03-02 03:30
> @patricks If you're interested a related task is to move the code related to func updateAssociatedContent() into the relevant presets in the Common Tags screen. It would require refactoring the logic and associated views into a separate class or classes.

Actually, because this is also needed for quests and it's actually pretty ugly I'm going to start working on this myself.
