### ISSUE TITLE
Cannot delete node

### ISSUE THREAD

**Issue by habi** [bryceco/GoMap#405] opened 2020-08-07 12:32 UTC
With Version 1.9.2 (1920) I cannot delete nodes anymore, as can be seen in the short screencast [1] below.
Tapping the 'Delete' button does not do anything.

![delete](https://user-images.githubusercontent.com/1651235/89646692-8a105980-d8bc-11ea-9a7e-b921a200b85d.gif)

[1] Converted from .mov to .gif with https://github.com/thevangelist/FFMPEG-gif-script-for-bash :)

**Comment by bryceco** [comment] 2020-08-07 14:22
1.9.1 and 1.9.2 have a problem where the ruler window is capturing taps meant for the buttons in front of it. Either revert to 1.9.0 in TestFlight or tap vary carefully along the top of the button.

**Comment by dieterdreist** [comment] 2020-08-07 15:24
as a workaround, turn the device to landscape

**Comment by habi** [comment] 2020-08-07 19:31
> 1.9.1 and 1.9.2 have a problem where the ruler window is capturing taps meant for the buttons in front of it.
> 
Good to know, I just wanted to make sure that you know it :)
> Either revert to 1.9.0 in TestFlight or tap vary carefully along the top of the button.
> 

No need to revert, I’ll wait for an update, whenever that’s ready.

**Comment by habi** [comment] 2020-08-07 19:32
> as a workaround, turn the device to landscape

Great tip, thanks!

**Comment by bryceco** [comment] 2020-08-08 00:36
Leaving this open so people can find the cause/solution.

**Comment by bryceco** [comment] 2020-08-09 16:45
Fixed in 1.9.5

**Closed by bryceco** 2020-08-09 16:45 UTC
