### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by gnafron** [bryceco/GoMap#103] opened 2016-09-17 17:33 UTC
I'm a French heavy user of your app, that is very usefull when I don't want to turn on my computer to do some simple edits, so I would like to translate it in French, but as it is closed-source, I didn't find a way to do it, or an already-opened issue. Is it possible, or is it not in your plans at all ?

**Comment by nickel715** [comment] 2016-10-02 15:27
I'm german (heavy ;)) user, I would help to translate Go Map in german

**Comment by Husim** [comment] 2018-07-07 20:00
I would like to help translate "Gomap!!" in russian.

**Comment by higa4** [comment] 2018-07-14 12:09
I would like to help translating in Japanese.

**Comment by xendez** [comment] 2018-09-26 08:43
And I would like to translate to Portuguese. Transifex is the most used one, but there are others like translatewiki, poeditor, crowdin,..

**Comment by bryceco** [comment] 2018-10-02 07:37
Now that the app is hosted under a permissive license on GitHub it is possible to use Transifex to start translating it (which wasn't possible without payment before). I'll try to upload a localization file in the near future that you can being translation work on.

**Comment by gnafron** [comment] 2018-10-02 16:03
Thank you for having made the app open-source ! I will be present when translation will open.

**Comment by wtimme** [comment] 2018-10-08 22:49
I've started adding localization for German. As you can tell from my changes, I've gone ahead and replaced the localized string keys that consists of the actual translation with underscore identifiers, e. g. `Move selected object?` becomes `confirm_move_alert_message`, making it more independent from the Base localization.

I don't know if this is the best way to go, but it seems practical. Input is always welcome.

**Comment by wtimme** [comment] 2018-10-22 20:53
Hey guys,

When starting to localize the app (thanks again for open-sourcing this!), I came across two open questions that I would like to discuss with you.

### Translation keys

At the moment the app uses the (English) base translation for strings (e. g. `Login successful`). This is potentially error-prone, since one might forget to also update the key in the `Localizable.strings` files.

From my experience, a more fail-safe approach is to use keys with words concatenated by underscores (e. g. `login_successful_alert_title`).

### Localizing the storyboard

To be honest, I'm not very experienced with localizing storyboards. Most if not all localization that I have been working with in the past were done programmatically, e. g. in `viewDidLoad()`. I found out strings in Storyboard can be localized using some arbitrary identifiers for the outlets. The readability is not very nice, and the identifier is changed once the element is removed and added again.

I came across the article _[Easy XIB and Storyboard Localization:
Apply DRY to make it maintainable][1]_. Mario Negro outlines how to utilize **User Defined Runtime Attributes** to be able to localize controls using translation keys (like the ones I propose above).

Does anyone have suggestions, ideas or experience they can share? I'd like to go ahead with making it localizable, but would like to get some input first. Thanks in advance!

[1]: https://medium.com/@mario.negro.martin/easy-xib-and-storyboard-localization-b2794c69c9db

**Comment by tordans** [comment] 2019-04-08 17:01
Personally, I feel fine with the english-only UI.

Adding localization to any app is a huge hassle and has a quite few downsides. For example:
- Its harder to develop, since there is an abstraction between the place where the code handles the text and the text itself
- Its hard to develop whenever you need to wrap items inside a translation
- One needs a translation workflow, to push translaters to update the translation and test it before the app is shipped
- The testing-setup needs to handle multiple translations
- The app needs to handle missing translation; fallback to EN
- The app needs a config to change translations, so people can create reports in english
- There will be text fields that are to small for the translation, those will be new bugs to come
- What about right to left languages
- …

**So, are we really sure we want to do this?** 
Will it increase the usage in such a way, that make the additional effort worth it?

**Comment by wtimme** [comment] 2019-04-09 19:40
Thanks for weighing in on this, @tordans!

From my attempts, I can confirm that it will be quite some hassle. For example, I looked into how to localize the ruler ("x meters", "y foot"), and figured that we probably need handling for plurals. Even though is is technically possible, it is quite some effort. Add this to the questions I raised above,

> Will it increase the usage in such a way, that make the additional effort worth it?

No, I don't think so at the moment.

**Comment by 1ec5** [comment] 2019-04-09 20:31
> For example, I looked into how to localize the ruler ("x meters", "y foot"), and figured that we probably need handling for plurals.

These particular details don’t require translation at all, as long as you use NSLengthFormatter or NSMeasurementFormatter.

**Comment by KovalevArtem** [comment] 2020-06-06 21:47
The issue with the localization of the interface has not yet been decided?

I am ready to help in the translation into Russian.
You can use Weblate. It is completely free for open source projects.
(This service is much more convenient than Transifex. In addition, he has open source!
For example, this service uses [OsmAnd](https://hosted.weblate.org/projects/osmand/))

**Comment by bryceco** [comment] 2020-06-07 04:27
I submitted a request to Weblate for free hosting. They say they process such requests monthly so it might be a while. Attached is the xliff file if you want to take a look and provide feedback (there are lots of free xliff apps you can download if you want to get started). There are 537 strings currently.

[en.xliff.zip](https://github.com/bryceco/GoMap/files/4741393/en.xliff.zip)

**Comment by KovalevArtem** [comment] 2020-06-07 07:41
@orangesunny

**Comment by wtimme** [comment] 2020-09-03 19:20
> Weblate [...] say they process such requests monthly so it might be a while.

Any update from them, Bryce?

There are other tools that we could use in case they decline, all with a free plan for Open Source projects:

- [POEditor](https://poeditor.com)
- [Transifex.com](https://www.transifex.com)

---

> Attached is the xliff file if you want to take a look and provide feedback

For people with Xcode available, you can

1. Open the project
2. Add your language (under _Project_ > _Info_ > _Localizations_)
3. Click _Editor_ > _Export for Localization..._
4. Download a Xliff software (e. g. [XLIFFTool](https://apps.apple.com/lv/app/xlifftool/id1074282695?mt=12)
5. Open the exported files for your language and translate

After translating, you can import the files (_Editor_ > _Import Localizations..._) and test them in the app.

**Comment by KovalevArtem** [comment] 2020-09-04 20:16
> There are other tools that we could use in case they decline, all with a free plan for Open Source projects:
> 
> * [POEditor](https://poeditor.com)
> * [Transifex.com](https://www.transifex.com)

These are terribly inconvenient translation services in my opinion.
Instead of those listed by you, I would recommend Crowdin ...

But it's better to use **Weblate**. As I wrote above!

**Comment by bryceco** [comment] 2020-09-08 00:42
Apparently Weblate activated my request but the notification to me got lost. It’s at https://hosted.weblate.org/projects/go-map/app/

**Comment by KovalevArtem** [comment] 2020-09-12 16:35
Please update your app in TestFlight.
The application is fully translated into **Russian**, **Norwegian** and **Japanese**. I wanted to check the translation directly in the application!

**Comment by KovalevArtem** [comment] 2020-09-12 16:37
I think that the issue can be closed...

**Comment by wtimme** [comment] 2020-09-12 16:55
Would be great to have the translations automatically updated whenever a new version is built. But that couls be a dedicated issue.

**Comment by bryceco** [comment] 2020-09-12 17:06
We need automation to automatically update xliff.en when code is committed. Once it's pushed to GitHub I believe the weblate site will then automatically pull that every 24 hours so translators get make updates. And then we need automation to push those translations back to GitHub.

**Comment by orangesunny** [comment] 2020-09-13 14:19
@bryceco, yes, Weblate push and pull automatically. You can set up the "age of changes to commit" on https://hosted.weblate.org/settings/go-map/app/#vcs.

Also, check out the "Documentation" buttons at https://hosted.weblate.org/projects/go-map/app/#alerts. It will guide you through some other settings to make your localization process more smooth :)

**Comment by bryceco** [comment] 2020-09-13 23:44
I understand how Weblate can push/pull, but that doesn't help with automatically doing the Export/Import of XLIFF files. There are still a lot of manual steps:
* Run Export...
* Copy files from the exported folder back into the source tree
* Commit and Push
...weblate stuff happens....
* Import each language back into Xcode

**Comment by bryceco** [comment] 2020-09-14 05:26
I’m releasing a TestFlight soon with translations. A couple notes: 
* The strings uploaded to weblate were incomplete due to some files not being marked as localized. That means there will be some additional strings to translate for languages that were already at 100%
* Due to my own lack of understanding of how translations get merged I had to manually merge a lot of strings. This resulted in some strings that were previously translated being lost, but I t’s a fairly small percentage. 
* For reasons I don’t understand the Croatian translation refused to import. I’ll try again in a few days when I update the other languages.

**Comment by wtimme** [comment] 2020-09-14 13:36
Could someone add a few lines to the README that explain how to pull/update the translations? I found the Weblate documentation a bit confusing.

That would also allow others to do the same and test the translations locally.

Thanks for your effort!

**Comment by sikmir** [comment] 2020-09-14 13:55
> Could someone add a few lines to the README that explain how to pull/update the translations? I found the Weblate documentation a bit confusing.

You can clone git repo:

`git clone https://hosted.weblate.org/git/go-map/app GoMap`

or add remote to existing one:


`git remote add weblate https://hosted.weblate.org/git/go-map/app`

**Comment by bryceco** [comment] 2020-09-14 16:13
I clearly did it the wrong way but I don't know the correct way:
* On Weblate I selected "download translations as zip file". This gave me a bunch of xliff files locally. 
* In Xcode I choose project > Editor > Import Localizations and selected an xliff to import
* Here it got ugly: when Xcode imported it put the translations under the en.lproj folder instead of the appropriate language folder, so I manually copied the strings to the correct locations after importing each language.

**Comment by sikmir** [comment] 2020-09-14 18:31
> I’m releasing a TestFlight soon with translations.

All untranslated strings appears in UI as empty ones, but default English should be used for such strings.

**Comment by bryceco** [comment] 2020-09-14 18:42
Which language? The Finnish translation added empty strings rather than leaving them undefined.

**Comment by sikmir** [comment] 2020-09-14 18:46
> Which language? The Finnish translation added empty strings rather than leaving them undefined.

Yes, I'm trying Finnish. Is it possible to use default English strings instead of empty ones if translation is not available?

**Comment by bryceco** [comment] 2020-09-14 18:55
It is, and it works for the other languages, but the Finnish translation was done incorrectly. Instead of leaving the translation as "undefined" the translation is instead an empty string. It needs to be fixed on weblate.

**Comment by higa4** [comment] 2020-09-14 23:50
Language fallback by English seems to be working fine in Japanese. Thanks for the effort of i18n.

**Comment by sikmir** [comment] 2020-09-15 07:53
@bryceco Just in case, Weblate supports adding screenshots to make it clear (and avoid ambiguity) for translators where particular string comes from. For example https://hosted.weblate.org/screenshots/openorienteering/mapper/. That would be really helpful.

**Comment by KovalevArtem** [comment] 2020-09-15 08:47
These words can also be added to the translation
![IMG_1090](https://user-images.githubusercontent.com/36500228/93188106-3f9abc00-f749-11ea-99f0-9d40caee6d8a.PNG)

**Comment by sikmir** [comment] 2020-09-15 08:52
> These words can also be added to the translation

By the way, after switching to TestFlight version, GoMap stops working for me, it shows "not found" on each zoom.

**Comment by dieterdreist** [comment] 2020-09-15 09:02
same for me. Imagery is still shown, but no data is loaded...

**Comment by higa4** [comment] 2020-09-15 09:17
I encountered the same issue few days ago and probably solved temporally as below...
Uninstall test ver. -> Install production ver. & check if OSM data is downloaded -> Uninstall production ver. -> Install test ver.

**Comment by sikmir** [comment] 2020-09-15 09:20
> I encountered the same issue few days ago and probably solved temporally as below...
> Uninstall test ver. -> Install production ver. & check if OSM data is downloaded -> Uninstall production ver. -> Install test ver.

It works for me!

**Comment by dieterdreist** [comment] 2020-09-15 09:33
deleting the testflight version and reinstalling it worked for me (no need to temporarily install the other version)

**Comment by rouelibre1** [comment] 2020-11-29 00:44
Is @gnafron still active ? I'd love to see the app translated in French and I'd be happy to do it myself, but I'm concerned about the quality of the translations that I would deliver. So I would need some help.

**Comment by gnafron** [comment] 2020-11-29 16:36
@rouelibre1 Yes I am, currently seeing what has been done and translating new strings

**Comment by bryceco** [comment] 2020-11-30 00:48
> @rouelibre1 Yes I am, currently seeing what has been done and translating new strings

Wow you plowed right through them! Nice!

**Comment by bryceco** [comment] 2021-02-09 08:11
We've got a number of translations completed and I feel like the workflow is stable, so I'm closing this 🎉

**Closed by bryceco** 2021-02-09 08:11 UTC
Labels: enhancement, help-needed, in-progress
