### ISSUE TITLE
Problems with some Fields in the Editor

### ISSUE THREAD

**Issue by Icebird2000** [bryceco/GoMap#778] opened 2024-07-02 19:34 UTC
There is a Problem with the „Description“, „Fix Me“ and the „Note“ fields. 
![image](https://github.com/bryceco/GoMap/assets/1193280/7dc198ce-e1a6-44cb-9bca-0d0143955ebd)
The Format and translation is wrong (should be like the ‚Mapillary Image ID’) and if you swipe from right to left and press delete you cannot edit this fields without leaving the editor. 
![image](https://github.com/bryceco/GoMap/assets/1193280/ee67f486-7c85-4e3d-ada5-94549c352640)
Here is a sample after deleting a multi line Text. 

In the Tags view the fields have a gray box and autofill is active but the previous and next fields are missing. 
![image](https://github.com/bryceco/GoMap/assets/1193280/1c939780-2873-46b9-88a9-f7078d84cc15)
here are the fields
![image](https://github.com/bryceco/GoMap/assets/1193280/25a0de9d-1455-43e6-8ae1-6536f4ac8afc)

**Comment by bryceco** [comment] 2024-07-03 05:31
Those fields are special because they allow entering multiple lines of text (UITextView vs UITextField).

If I understand correctly there are 4 different bugs:
1. Swiping to delete text breaks the control (fixed in ebcd998be920c265870c3c7c4cf6a24758ecee52)
2. Background color is wrong when using Dark Mode (fixed in eb5938c108225fe09a73afadb6c59200bc4fadc1)
3. In "All Tags" there is no Next/Previous toolbar (fixed in f75163ae1e80fd6044fdc6a6fc4ccfa48027eccd).
4. "Unknown" is being displayed in the wrong language

I can't figure out what is happening with the last one. What version of the app is this?

**Comment by tordans** [comment] 2024-07-03 05:39
> "Unknown" is being displayed in the wrong language
> I can't figure out what is happening with the last one. What version of the app is this?

![image](https://github.com/bryceco/GoMap/assets/111561/8807fd02-f357-424b-9ea7-75a254a14a1b)
4.2.4 4204

**Comment by bryceco** [comment] 2024-07-03 05:49
Yeah it looks like it's a version that is half-translated.

**Comment by Icebird2000** [comment] 2024-07-03 07:11
Version is 4.2.4 (4204) from the AppStore
It happens, if you set the language of the app OS wide (Settings ->  Go Map!! -> Language to German) and change the language in Go Map!! under Settings to English. 
I thing, this is sometimes common on other devices because you want the english tag names.

**Comment by dieterdreist** [comment] 2024-07-03 08:36
Yesterday I encountered a check_date and opening_hours:check_date (or the other way round), and both had a plus-button, but while the check_date plus button updated the date, the other button opened the camera 

sent from a phone

**Comment by Icebird2000** [comment] 2024-07-03 08:43
> Yesterday I encountered a check_date and opening_hours:check_date (or the other way round), and both had a plus-button, but while the check_date plus button updated the date, the other button opened the camera sent from a phone

Yes, i think this is by design. The plus-button on the opening_hours tag opens always the camera.

**Comment by Icebird2000** [comment] 2024-07-03 12:34
By the way, the key should be check_date:opening_hours 
[Wikientry - check_date](https://wiki.openstreetmap.org/wiki/Key:check_date)
If you use this key, everything is working correct.

**Comment by bryceco** [comment] 2024-07-03 15:36
> It happens, if you set the language of the app OS wide (Settings -> Go Map!! -> Language to German) and change the language in Go Map!! under Settings to English.

Okay that makes sense. The translation for “Unknown” for those fields isn’t coming from the presets, but I can change it so it does.

**Comment by bryceco** [comment] 2024-07-03 15:42
> opening_hours:check_date

Nice, we just need to do the test for check_date  before anything else (e.g. website:check_date).

**Comment by dieterdreist** [comment] 2024-07-03 15:52
no, the object is this and the tag was check_date:opening_hours

https://www.openstreetmap.org/way/30698972

sent from a phone

**Comment by Icebird2000** [comment] 2024-07-03 18:57
I don’t know if I should open a new case, but i found another field error. Possible with dark mode. If i change the „No - Yes“ Button to no or yes the text in the field is not shown. If i click in the field it appears. 

![image](https://github.com/bryceco/GoMap/assets/1193280/f3354f3d-b5e3-4cce-903e-bd001e78b9e7)

![image](https://github.com/bryceco/GoMap/assets/1193280/72859c9c-5552-4ef6-9887-384722bfa505)

**Comment by bryceco** [comment] 2024-07-03 20:48
> the tag was check_date:opening_hours

Turns out we weren't looking for any variants of check_date:*, so I've updated it to do that.

**Comment by bryceco** [comment] 2024-07-03 20:54
> If i change the „No - Yes“ Button to no or yes the text in the field is not shown. If i click in the field it appears.

That's by design. We support displaying or typing in a custom value so we have to show the text when you click the text field. See https://taginfo.openstreetmap.org/keys/backrest#values for examples of edge cases.

**Comment by bryceco** [comment] 2024-07-03 20:55
Closing this, please open a new ticket for new bugs :)

**Closed by bryceco** 2024-07-03 20:55 UTC
