### ISSUE TITLE
Duplicate nodes with GoMap?

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#333] opened 2020-06-03 17:14 UTC
I have had a few cases, where mappers have (had to) rework something I mapped while walking. Their comments where, that they removed duplicate nodes.

I could not pinpoint the issue further, yet, but I wanted to start collecting instances in this Issue

* https://osmcha.org/changesets/86142530/?aoi=f0b96083-171b-4bbb-af00-c38f24cb7319
* https://osmcha.org/changesets/86035743/?aoi=f0b96083-171b-4bbb-af00-c38f24cb7319
  * Assumed to be "broken" in https://osmcha.org/changesets/86002377/?aoi=f0b96083-171b-4bbb-af00-c38f24cb7319

(There are others but I need to find them again.)

**Comment by bryceco** [comment] 2020-06-03 19:54
Duplicate of #206. My guess is that there is some combination of undo/redo that triggers this, but any information is useful!

**Closed by bryceco** 2020-06-03 19:54 UTC
