### ISSUE TITLE
[3.8.4] Direction indicator not shown / Selected Option not preselected 

### ISSUE THREAD

**Issue by Icebird2000** [bryceco/GoMap#662] opened 2023-04-20 21:33 UTC
Hello and thanks for the brand new Version. 

I found two possible bugs:

first the direction indicator is not shown in some cases (the yellow circle in the middle):
![IMG_1852](https://user-images.githubusercontent.com/1193280/233491359-faf6a5fb-f3b8-4c17-920c-2d08185c8889.jpeg)

the second is, in the old version the selected value was indicated by the visible buttons here the Value locked=yes :
![IMG_0410](https://user-images.githubusercontent.com/1193280/233491874-53706368-3fcb-4402-b9c5-2fcdae3d65a9.jpeg)

but in the new version it shows the value as a word (thats is great), but not with the buttons 

![IMG_1854](https://user-images.githubusercontent.com/1193280/233492309-2ff529d1-0b79-4d13-973d-2263c710c612.jpeg)

**Comment by bryceco** [comment] 2023-04-20 23:10
Can you post the ID/location of the misbehaving direction indicator node?

**Comment by bryceco** [comment] 2023-04-20 23:44
First issue is "works as intended", second issue fixed in 0d1c5a9d20f60ad857809c3cacae474ab9dc225a

**Closed by bryceco** 2023-04-20 23:44 UTC

**Comment by Icebird2000** [comment] 2023-04-21 19:14
Ok, thanks again. 
Funnily you left out the last part: 
(or, depending on context, [highway](https://wiki.openstreetmap.org/wiki/Key:highway)=*)
But i understand root of the Problem and try to fix this by my side. Source of this Problem is tagging of [street parking](https://wiki.openstreetmap.org/wiki/Street_parking) which separates the way. 
till now i doesn’t see this as an problem, but i see that this is hard to detect for renderer and other programs.
