### ISSUE TITLE
Testflight: Random Crash in Tag Editing

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#335] opened 2020-06-07 08:53 UTC
I experienced random crashes with the last two testflights (not the current one from today; I did not test this, yet).

I wanted to create this issue to have place to communicate about it.

Unfortunatelly, I was not able to really find out what triggers the crash.
I had them in the preset selection, in the common tags and in the all tags view …

They started after the shop-presets where added to the presets.

However, those crashes delete the recent mapped data that was not yet commited to OSM, so they are really annoying …

One I idea I had is, they might be related to some background data-pull like goMap pulling new editor-layer-index files or maybe the new shop-presets?

I will continue to send the crash reports and hope those help(?)

**Comment by bryceco** [comment] 2020-06-07 21:53
I believe the crash is caused by the wikipedia lookup code firing when you tap the cell containing the Add New button. Should be fixed now that the Add New button row no longer exists.

**Closed** 2020-06-07 22:05 UTC
