### ISSUE TITLE
(?) Icon for "new node"

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#316] opened 2020-04-09 05:04 UTC
Now that the new Icons make the app look even nicer, the old (?)-icon that is visible when placing a new node looks out dated.

Brainstorming:
* A circle with a "+" in in, in some color that is not used like red
* A map marker with a plus in it (https://icons.getbootstrap.com/icons/geo-alt/, https://fontawesome.com/icons/map-marker?style=solid
* Or stick with the circle+? but as an SVG flat icon

![IMG_6125](https://user-images.githubusercontent.com/111561/78859374-6a147a80-7a2f-11ea-92b3-edefa6138bef.jpg)

---

Side note: The color of this icon could also be an opportunity to pick up brand colors, like I commented on at https://github.com/bryceco/GoMap/issues/236#issuecomment-593084624 
> how could the icon design be used inside the app, so the style gets picked up again somewhere?

**Comment by bryceco** [comment] 2020-04-09 06:34
Duplicate of #315?

**Closed** 2020-04-11 21:58 UTC
