### ISSUE TITLE
Beta: Crash + error

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#531] opened 2021-06-17 03:36 UTC
I installed the current beta today. Afterwards I was not able to start the app again. I got two crashes right after another with two incident reports send each time. Did this twice.

Then removed and reinstalled the app. Got a DB error afterwards. 

Now my custom presets and image layer are gone but the app seems to run for now. 

Is there a way to build some (more?) automated tests about the custom image layer and tag presets? I think those get lost a lot and cause errors again (they are also very important IMO). 

Another idea would be to standardize those data with a public spec and save them in the OSM user settings via API so that all Editors may use them. (Wanted to write a more detailed issue about this for a while...)

![image](https://user-images.githubusercontent.com/111561/122327074-92e6a880-cf2d-11eb-8f07-d4bfe81e95b0.png)

**Comment by bryceco** [comment] 2021-06-17 16:33
In the future if you don't want to lose your customizations you should probably refrain from deleting/reinstalling and instead just download a known-good version from the App Store.

**Comment by bryceco** [comment] 2021-06-17 16:59
Actually I would prefer that you not delete the app and instead revert to an older build. That way we can confirm if the bug gets fixed in the next update.

**Comment by tordans** [comment] 2021-06-17 18:34
For me, part of the debugging was to figure out, that it probably has to do with that part of the app. Unless that is something the automated error reports tell you already in enough clarity – then I will stop debugging this way.

**Comment by habi** [comment] 2021-06-17 19:54
I also ran into this issue (minus the lost customisation, I don't have any).
The update went bonkers, the only way to fix it (in my opinion) was a removal of the (TestFlight beta) app, reboot of the phone and a reinstallation of version 2.30. (2300).
I *did* send the crash report twice, too.

**Comment by tordans** [comment] 2021-06-17 21:17
I have the beta running. Reinstalled  via TestFlight after removing it. 

New info: I just opened it again and got the same message from the screenshot above (Database). Didn't do any actual mapping in the meantime though, just panned and looked around.

**Comment by bryceco** [comment] 2021-06-18 01:22
I received 5 crash reports indicating a crash while initializing user-defined presets, so there's definitely a problem there.
However if I delete the app, install from the app store, create a custom preset, and then upgrade to the current beta I don't see a crash. Can you reproduce it that way, and if so send me what you're using for your presets?

Note that because Swift saves data in a new format you'll always crash when trying to downgrade to a pre-Swift version.

**Comment by bryceco** [comment] 2021-06-18 01:36
You can ignore the database error message: It will appear on any fresh install where there is no database to read. I'll fix it before the next beta.

**Comment by tordans** [comment] 2021-06-18 04:21
New info: I did changes yesterday after writing here and kept them not-committed. Closed the app. Today there was the DB error + those changes are gone.

**Comment by tordans** [comment] 2021-06-18 04:57
> However if I delete the app, install from the app store, create a custom preset, and then upgrade to the current beta I don't see a crash. Can you reproduce it that way, and if so send me what you're using for your presets?

I tried it but did not get the AppStore version running again; I send you the details via email.

I am pretty sure I had only one preset at this time which should look like this:

- Name: `bicycle_parking:position`
- Activate on: `amenity=bicycle_parking`
- Provide Key: `bicycle_parking:position`
- Values: [`sidewalk`, `lane`, `private_property`]

Btw, is it by design or is it just me: I cannot find the preset button in the new app anymore.

I also had quite a few custom map layer from this list https://github.com/codeforberlin/mapproxy-config

**Comment by habi** [comment] 2021-06-18 13:37
As of today, I cannot even start the app anymore, it crashes immediately.
Yesterday the version 2.3.0 informed me about the database error and then worked for a bit.

I've sent a report through TestFlight, is there anything else I can help to debug this?

**Comment by bryceco** [comment] 2021-06-18 21:34
> I tried it but did not get the AppStore version running again; I send you the details via email.

You have to delete the app in order to download/install the AppStore version. There's no way to downgrade in-place (and have the app run).

> Btw, is it by design or is it just me: I cannot find the preset button in the new app anymore.

It hasn't moved, it's at the bottom of Common Tags.

**Comment by bryceco** [comment] 2021-06-18 21:38
> I've sent a report through TestFlight, is there anything else I can help to debug this?

I'm guessing that one of the undo/redo actions isn't being properly decoded. It could be a fairly basic operation or something more obscure, it's hard to say.

**Comment by bryceco** [comment] 2021-06-19 00:29
It looks like modifying any member of a relation might have been the culprit. Doing so definitely causes a crash when reloading.

**Comment by bryceco** [comment] 2021-06-27 16:39
I believe all of these bugs have been resolved. If you still can find a crash after upgrading from App Store release please reopen!

**Closed** 2021-06-27 16:39 UTC
