### ISSUE TITLE
automatic update for survey:date

### ISSUE THREAD

**Issue by JLZIMMERMANN** [bryceco/GoMap#345] opened 2020-06-20 20:20 UTC
When checking something is still existing a button updating survey:date is welcome.

**Comment by tordans** [comment] 2020-07-05 08:01
I find changing or adding the dates for the survey_date very tedious so having the UI help me would be great.

My first though is, to not have it happen automatically but by an „update“-Action next to the survey_date=<date>-Tag.

The reason is, that I might not survey all feature of a thing, so the auto update might not be correct and happen without me wanting it to.

Example: We have water pumps where the survey_date suggests that someone checked if the pump still works. But I sometimes just add a ref=* or move the position or something like this but I don’t always check if all attributes are still correct (like the pump:status=broken for example).

—

Ping to https://github.com/bryceco/GoMap/issues/116 for reference.

**Comment by bryceco** [comment] 2020-07-19 03:22
As noted this is a duplicate of #116, but since I’ve been adding similar things to All Tags lately I’ll support these tags there.

**Closed** 2020-07-19 23:09 UTC

**Comment by bryceco** [comment] 2020-07-19 23:11
In All Tags there is now a button next to survey:date (and all of its synonyms) that will set the current date

**Comment by yellowsoar** [comment] 2021-10-04 08:00
For someone who search the keyword "check_date" before opening a feature request and finally get here...
I mean... like me. (LOL)

![2021-10-04_15-48-43](https://user-images.githubusercontent.com/4775704/135814572-6463027d-84be-474d-86ec-1f00e1766a34.png)
