### ISSUE TITLE
User quest overwrites built-in quest

### ISSUE THREAD

**Issue by nicolashohm** [bryceco/GoMap#670] opened 2023-06-03 07:32 UTC
Hi, I really enjoy the quests feature and currently building my own quests. Though, I think I found a bug:

## Steps to reproduce

Create a quest which modifies the `opening_hours` tag. Choose any icon.

## Actual behavior

The created quest does not show up as a user quest, but instead the built-in quest is overwritten. 

There seems to be no way to delete this quest either.

## Expected behavior

The quest created by the user is shown as a separate quest in the list and can be modified/deleted.

**Comment by nicolashohm** [comment] 2023-06-03 08:43
If it helps [here](https://github.com/nicolashohm/GoMapQuests/blob/1eb51f5aba1ff27645c88a16aa989a5d20752b34/quests/opening_hours.json) is an example json which you can import. Surprisingly, it even works with two different quests for the opening_hours key. It also works as intended, I only see the quests for amenity or shop tags as far as I can see

**Comment by bryceco** [comment] 2023-06-21 00:04
Thanks for this report, and apologies for the delay responding. 

The intended behavior is that the quest name (in your local language) uniquely identifies the quest, so if two quests have the same name then the most recently added quest survives and the previous quest is overwritten. If your quest is named "Add Opening Hours" (for English, or your localized equivalent) then it should replace the built-in quest of the same name. Likewise in your example on GitHub only the second quest will stick, and the first one will be lost. 

Therefore part of your report is "works as expected", BUT there is also bug where the quest become uneditable if it replaces a built-in quest. I'd be happy to hear feedback about whether replacing built-ins is a desirable feature.

**Comment by nicolashohm** [comment] 2023-06-21 09:51
I just tried to import the quests with new names which are different from built-in ones ([import json](https://github.com/nicolashohm/GoMapQuests/blob/17e357086832ce87c7723bac3496b1e309f201c5/quests/opening_hours.json)) and it worked, the quests appeared as new quests in the list.

> the quest become uneditable if it replaces a built-in quest.
Fine for me that the built-in quest is overwritten if the user quest has the same name, but at least it should be editable and deletable then! 

>  I'd be happy to hear feedback about whether replacing built-ins is a desirable feature
But not allowing overwriting the built-in quests and showing the user quests below is in my opinion even better/more intuitive. I also don't think it's necessary to provide the possibility to overwrite the built-ins, if users want to customize the built-in quests like me, they can just create new quests and disable the built-in ones. I see no disadvantage here.

**Comment by bryceco** [comment] 2023-07-03 23:59
Mostly fixed in 4661a230950232261a081c320fd7c109df97af91

**Closed by bryceco** 2023-07-03 23:59 UTC
