### ISSUE TITLE
Need to be able to reallign aerial imagery 

### ISSUE THREAD

**Issue by bryceco** [bryceco/GoMap#32] opened 2013-01-27 17:11 UTC
An example is attached where the Bing Imagery is out by 2 metres in one direction and one in the other. The Trig point is North of its actual location (between the end of its right leg and the low wall) and the roads whilst aligned to the trig point are not aligned to the imagery which is out of kilter.

The Bing imagery in general is not geolocated to much more than a few meters accuracy making the ability to realign important at high magnification.

Also the trig point symbol needs a mark for the centre like crosshairs.

![image](https://f.cloud.github.com/assets/279734/101118/89b9e680-68a4-11e2-8e8b-ab8093f7ddd7.png)

**Comment by hsn10** [comment] 2018-07-19 06:50
Yes. This is very needed indeed.

**Comment by fntagit** [comment] 2018-08-18 08:51
Yes, producing good mapping work is difficult when the imagery is not welle aligned, which happens very often with Bing and other sources. In addition, it would be very useful if the user-defined offset would be retained for each source: switching imagery sources is often needed during a single session, to use the most visible/precise features of each one.

**Comment by dieterdreist** [comment] 2018-08-19 08:07
I am not convinced translating the imagery is a solution for badly aligned images. Usually it is a result of a coarse elevation model and the problem is distortion rather than something that can be fixed by moving the imagery. This is particularly evident in hilly areas or where abrupt elevation changes occur (retaining walls, cliffs, etc.)

**Comment by fntagit** [comment] 2018-08-19 14:38
Of course, simply shifting imagery is not THE solution to all problems, This is indeed especially true for large areas, where distortion and inaccurate elevation models must be accounted for. Nevertheless, when mapping smaller areas, beeing able to align the imagery with some known features helps a lot, and is a recommended practice according to the OSM wiki. There are even projects to automate the sharing of offsets (Imagery Offset Database, True Offset Process).

**Comment by TheAdventurer64** [comment] 2020-08-03 18:32
When will this be available?

**Comment by bryceco** [comment] 2020-08-03 19:05
Whenever somebody volunteers to implement it.￼

**Comment by mellangr** [comment] 2024-04-30 10:19
This feature is important for professional mappers, even though it may not be prominently used by casual users. In some countries that use their own unique coordinate systems, the transformation often does not occur perfectly. In such cases, what seems to be a precise orthophotomap may have a consistent offset of several meters. For example, in the Ukraine - Cherkasy 2021 layer, the imagery is out of alignment:

![IMG_5B01F10A81AC-1](https://github.com/bryceco/GoMap/assets/20912330/0224f75d-85f2-41e4-bd48-6c5a3f78af1b)

![Знімок екрана 2024-04-30 о 13 17 40](https://github.com/bryceco/GoMap/assets/20912330/76919dbb-8fc6-414e-900f-b1e1fc7f6318)

It would be great to have a field in the layer properties where one could enter numbers to adjust its position, similar to what is done in iD and JOSM.

I would like to help implement this feature, but unfortunately, I do not have programming experience

**Closed** 2024-05-01 23:27 UTC
Labels: enhancement
