### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by TheAdventurer64** [bryceco/GoMap#458] opened 2020-11-01 22:02 UTC
![Uploading 97816541...]

**Comment by bryceco** [comment] 2020-11-02 00:30
Upload seems to be stuck

**Comment by TheAdventurer64** [comment] 2020-11-05 07:01
![image](https://user-images.githubusercontent.com/50059322/98208123-5fa55b00-1f02-11eb-8d6f-2444316323b7.jpeg)

**Comment by TheAdventurer64** [comment] 2020-11-05 07:02
![image](https://user-images.githubusercontent.com/50059322/98208257-a1360600-1f02-11eb-83ef-48e850d946b9.jpeg)

**Comment by bryceco** [comment] 2020-11-05 08:07
Can you reproduce it?

**Comment by bryceco** [comment] 2020-11-15 21:52
What's interesting about this bug is that the app contains only a single instance of the PushPinView, the object that displays the text, so there's no explanation for it appearing twice. Since it seems to be a one-off but and without steps to reproduce it I'm closing this.

**Closed by bryceco** 2020-11-15 21:52 UTC
