### ISSUE TITLE
Rotating the phone to landscape and back makes it impossible to get out of Webview

### ISSUE THREAD

**Issue by habi** [bryceco/GoMap#606] opened 2022-07-06 21:41 UTC
I love the integrated Wiki lookup of tags and use it quite a bit.
When rotating the phone to landscape and back it is impossible to reach the 'Done' button on the top left.
In the video the button is overlaid with the 'screen recording' marker, but in other cases it's the clock and location recording marker which hide the 'Done' button.

https://user-images.githubusercontent.com/1651235/177647458-d82db9a8-b700-4ea3-b8e4-fa1cdbb45b6c.mov

The only way (I found) to get out of this is force-quitting the app.
I'm running Go Map!! 3.1.4 (3104) on an iPhone 12 mini with iOS 15.6

**Comment by bryceco** [comment] 2022-07-07 00:47
Yes, that's a bug. You can go back to landscape and dismiss it, rather than force-quitting.

**Comment by habi** [comment] 2022-07-07 05:26
> You can go back to landscape and dismiss it

Thanks, I really didn't think of this! 🤪

**Comment by bryceco** [comment] 2022-07-28 20:32
I've tried fixing this but I'm at a loss about what the cause is. Maybe somebody else would like to take a look at it: https://github.com/bryceco/GoMap/blob/c18ce70de620ce36c6e72f59bc1df3f3b50d8cae/src/iOS/POI/POIAllTagsViewController.swift#L477

**Comment by patricks** [comment] 2023-02-23 20:32
I played around a bit with that problem, the same happens if I tap the "i" button on the main screen and rotate the wikipage screen (SFSafariViewController).

If I comment out the function `override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator)` in the `MainViewController` the problem is fixed in both cases. This would be a really easy fix. But I don't know exactly why this function / animation is required. Maybe @bryceco knows more about it?

**Comment by bryceco** [comment] 2023-02-24 01:04
That function simply updates the frame of the embedded MapView (which is the view that holds the various layers used for editing, aerial, etc. That view isn't tied to it's parent with constraints (because I wrote it before iOS introduced constraints, and then plugged up problems with fixes like this 😅) so I update the frame manually there. It's possible that function isn't needed anymore but it needs some testing to make sure.

**Comment by patricks** [comment] 2023-02-25 09:10
> 



> but it needs some testing to make sure

Thanks for the informations. Can I help you somehow with the testing? I already played around with the app with this code disabled and didn't find/see any problems.

**Comment by bryceco** [comment] 2023-02-26 01:09
It looks like at some point I added constraints that take care of setting the frame, and I just confirmed that the frame is updating correctly without the function you mention so deleting it is fine.  Send me a pull request! Thanks!

**Closed** 2023-02-26 17:02 UTC
Labels: help-needed

**Comment by habi** [comment] 2023-02-26 17:46
Awesome work, thanks!
