### ISSUE TITLE
pasting more specific values should not create multivalues

### ISSUE THREAD

**Issue by dieterdreist** [bryceco/GoMap#197] opened 2019-04-12 07:34 UTC
In the case of sometag=yes if you paste another , more specific value for the same key it would make more sense to overwrite the old value rather than keeping both.
E.g. if you paste building=apartments on building=yes, the result should be building=apartments rather than “yes;apartments”.
Generally I agree it is safer to keep both values when in doubt.
Alternatively you could warn and ask the user how to handle it (cancel, overwrite, combine).

**Comment by tordans** [comment] 2019-04-12 08:49
I believe this is solved in the comming version.
If I read the issues/PRs correctly, there will be two feature: paste & replace and paste & merge.
The issue you describe should be solved with that.

Details at 
- merge https://github.com/bryceco/GoMap/issues/169 / https://github.com/bryceco/GoMap/issues/169
- replace https://github.com/bryceco/GoMap/pull/158

**Comment by dieterdreist** [comment] 2019-04-12 22:04
What I would like is paste+merge+overwrite 

existing tags that are pasted should overwrite the values, but other tags would not be touched (no removal of tags). 
Maybe this is what paste+replace does (it wasn’t clear to me from the description).

**Comment by zlavergne** [comment] 2019-04-18 19:38
The implementation of #170 takes care of #169 and I believe it handles the situation @dieterdreist is describing. With that PR, there are 2 options:
1. Paste - (Merge) changes what's currently in Go Map to function like JOSM 
2. Replace Tags - replaces all tags in the target object with the tags in the copy buffer

Unless you disagree, I'm closing this as a duplicate of #169

**Comment by zlavergne** [comment] 2019-04-18 19:40
Duplicate of #169

**Closed** 2019-04-18 19:45 UTC
